$schema: https://azuremlschemas.azureedge.net/latest/commandJob.schema.json
code: model
command: |
  echo "Hello, world!"
  ls -la
  python train.py --training_data ${{inputs.training_data}} --reg_rate ${{inputs.reg_rate}}
inputs:
  training_data: 
    type: uri_folder
    path: azureml:diabetes-prod-folder:1
  reg_rate: 0.01
environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest #
compute: azureml:shahcluster # maybe local needs docker
experiment_name: DummyExperiment 
description: |
  # Azure Machine Learning "hello world" job
  This is a "hello world" job running in the cloud via Azure Machine Learning!
  ## Description
  Markdown is supported in the studio for job descriptions! You can edit the description there or via CLI.